### PR TITLE
Fix a couple of typos in Ironsworn Moves

### PR DESCRIPTION
**Pull request by scottbenton**
Hello @rsek!
I'm working on setting up an Ironsworn project with v2.0.0-2 and found a small typo here. Let me know if I need to do anything else to get this change everywhere in the repo it needs to go. Thank you for all your hard work on this, it is an incredible tool!

### CODE REVIEW

**Comment by rsek** [comment]
Hi @scottbenton, thanks for the catch and sorry about the delay on my reply. I'm doing some reorganization of the repo so that `main` is based on the last stable version (1.5.x), while `v2` is the unstable development version (next/2.0.0-X), so I'll merge it to the latter branch instead.

**Comment by rsek** [comment]
@scottbenton Oof, I'm having some difficulty getting github to cooperate with merging the changes while properly crediting you) -- could you do me a favour and rebase the changes to `v2`?

**Comment by scottbenton** [comment]
Updated it! Do you recall if the v2 branch is up to date with v2.0.0-2? I recall having some issues with an mismatch between `ironsworn/oracles/moves/ask_the_oracle/fifty_fifty` and `ironsworn/oracles/moves/ask_the_oracle/50_50`, but I'm not seeing that difference now between `moves.yaml` and `moves_core.yaml`.

Also, not sure if I need to update any of the i18n files, so please let me know if anything else needs done!

**Comment by rsek** [comment]
> Updated it! Do you recall if the v2 branch is up to date with v2.0.0-2? I recall having some issues with an mismatch between `ironsworn/oracles/moves/ask_the_oracle/fifty_fifty` and `ironsworn/oracles/moves/ask_the_oracle/50_50`, but I'm not seeing that difference now between `moves.yaml` and `moves_core.yaml`.

`fifty_fifty` is the target i've settled on for v2's release, but it's been a bit since i've regenerated the JSON files for v2, so they may not reflect that yet. basically, ID fragments after the first slash now match the regex `/^[a-z_]+$/` so that IDs have a predictable structure once array indices and table row ranges are in the mix.

**Pull request merged**
